# Generated by Django 5.2.16 on 2026-08-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HR_ADMIN', 'HR Admin'), ('HR_USER', 'HR User')], default='HR_USER', max_length=20),
        ),
    ]
