export interface Job {
  id: string;
  title: string;
  department: string;
  location: string;
  employmentType: "Full-time" | "Part-time" | "Contract" | "Internship";
  experienceLevel: "Entry" | "Mid" | "Senior";
  experience: string;
  applications: number;
  status: "Open" | "Closed" | "Draft";
  createdDate: string;
  salaryRange: string;
  vacancies: number;
  skills: string[];
  description: string;
  deadline: string;
}

export const jobsMockData: Job[] = [
  {
    id: "job-1",
    title: "Frontend Developer",
    department: "Engineering",
    location: "Hyderabad, IN",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    experience: "2-4 yrs",
    applications: 128,
    status: "Open",
    createdDate: "2026-07-10",
    salaryRange: "₹8L - ₹14L",
    vacancies: 3,
    skills: ["React", "TypeScript", "Tailwind"],
    description: "Build and maintain performant, accessible user interfaces for our recruitment platform.",
    deadline: "2026-08-30",
  },
  {
    id: "job-2",
    title: "Backend Developer",
    department: "Engineering",
    location: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    experience: "3-5 yrs",
    applications: 94,
    status: "Open",
    createdDate: "2026-07-12",
    salaryRange: "₹10L - ₹16L",
    vacancies: 2,
    skills: ["Node.js", "PostgreSQL", "AWS"],
    description: "Design and scale backend services powering candidate screening pipelines.",
    deadline: "2026-08-25",
  },
  {
    id: "job-3",
    title: "Full Stack Developer",
    department: "Engineering",
    location: "Bengaluru, IN",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    experience: "5-7 yrs",
    applications: 61,
    status: "Open",
    createdDate: "2026-07-15",
    salaryRange: "₹18L - ₹26L",
    vacancies: 1,
    skills: ["React", "Node.js", "Docker"],
    description: "Own features end-to-end across our web app and API layer.",
    deadline: "2026-09-01",
  },
  {
    id: "job-4",
    title: "Python AI Engineer",
    department: "AI/ML",
    location: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    experience: "3-5 yrs",
    applications: 210,
    status: "Open",
    createdDate: "2026-07-05",
    salaryRange: "₹14L - ₹22L",
    vacancies: 2,
    skills: ["Python", "PyTorch", "LangChain"],
    description: "Develop the AI resume screening and candidate ranking models.",
    deadline: "2026-08-20",
  },
  {
    id: "job-5",
    title: "ML Engineer",
    department: "AI/ML",
    location: "Hyderabad, IN",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    experience: "4-6 yrs",
    applications: 87,
    status: "Draft",
    createdDate: "2026-07-20",
    salaryRange: "₹16L - ₹24L",
    vacancies: 1,
    skills: ["TensorFlow", "MLOps", "Python"],
    description: "Build and deploy production ML pipelines for candidate scoring.",
    deadline: "2026-09-10",
  },
  {
    id: "job-6",
    title: "UI/UX Designer",
    department: "Design",
    location: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    experience: "2-4 yrs",
    applications: 143,
    status: "Open",
    createdDate: "2026-07-08",
    salaryRange: "₹9L - ₹15L",
    vacancies: 1,
    skills: ["Figma", "Design Systems", "Prototyping"],
    description: "Craft delightful, glassmorphic interfaces across the HR and candidate portals.",
    deadline: "2026-08-28",
  },
  {
    id: "job-7",
    title: "DevOps Engineer",
    department: "Engineering",
    location: "Pune, IN",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    experience: "5-8 yrs",
    applications: 52,
    status: "Closed",
    createdDate: "2026-06-28",
    salaryRange: "₹18L - ₹28L",
    vacancies: 1,
    skills: ["Kubernetes", "Terraform", "CI/CD"],
    description: "Own our cloud infrastructure and deployment pipelines.",
    deadline: "2026-07-30",
  },
  {
    id: "job-8",
    title: "Data Scientist",
    department: "AI/ML",
    location: "Remote",
    employmentType: "Contract",
    experienceLevel: "Mid",
    experience: "3-5 yrs",
    applications: 76,
    status: "Open",
    createdDate: "2026-07-18",
    salaryRange: "₹12L - ₹20L",
    vacancies: 2,
    skills: ["Python", "SQL", "Statistics"],
    description: "Analyze hiring funnel data to improve match-score accuracy.",
    deadline: "2026-09-05",
  },
  {
    id: "job-9",
    title: "QA Engineer",
    department: "Engineering",
    location: "Hyderabad, IN",
    employmentType: "Full-time",
    experienceLevel: "Entry",
    experience: "1-3 yrs",
    applications: 39,
    status: "Draft",
    createdDate: "2026-07-22",
    salaryRange: "₹6L - ₹10L",
    vacancies: 2,
    skills: ["Cypress", "Jest", "Manual Testing"],
    description: "Ensure quality across our frontend and API surfaces.",
    deadline: "2026-09-15",
  },
  {
    id: "job-10",
    title: "Cloud Engineer",
    department: "Engineering",
    location: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    experience: "3-5 yrs",
    applications: 45,
    status: "Open",
    createdDate: "2026-07-14",
    salaryRange: "₹13L - ₹19L",
    vacancies: 1,
    skills: ["AWS", "Azure", "Terraform"],
    description: "Manage and optimize our multi-cloud infrastructure footprint.",
    deadline: "2026-08-31",
  },
];

export const departments = ["Engineering", "AI/ML", "Design"];
export const locations = ["Hyderabad, IN", "Bengaluru, IN", "Pune, IN", "Remote"];
export const employmentTypes = ["Full-time", "Part-time", "Contract", "Internship"];
export const experienceLevels = ["Entry", "Mid", "Senior"];
export const jobStatuses = ["Open", "Closed", "Draft"];