# Generated by Django 4.2.26 on 2026-07-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resume_threshold',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum overall resume score required to auto-shortlist a candidate.', max_digits=5),
        ),
    ]
