# Generated by Django 4.2.26 on 2026-07-31 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0002_alter_candidate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_RESCHEDULED', 'Interview Rescheduled'), ('INTERVIEW_CANCELLED', 'Interview Cancelled'), ('OFFER', 'Offer'), ('CUSTOM', 'Custom')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Supports placeholders: {{candidate_name}}, {{job_title}}, {{company_name}}, {{status}}, {{interview_date}}, {{interview_time}}, {{interview_mode}}, {{meeting_link}}, {{location}}, {{interviewer_name}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='email_templ_templat_afa959_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('PHONE', 'Phone')], default='ONLINE', max_length=10)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_schedules',
                'ordering': ['-interview_date', '-interview_time'],
                'indexes': [models.Index(fields=['status'], name='interview_s_status_af310d_idx'), models.Index(fields=['interview_date'], name='interview_s_intervi_ec879c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='recruitment.application')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='recruitment.candidate')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='communications.emailtemplate')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='email_logs_status_e3be55_idx'), models.Index(fields=['recipient_email'], name='email_logs_recipie_00ae8d_idx')],
            },
        ),
    ]
